language: android
jdk: oraclejdk8
sudo: false

android:
  components:
  - tools                             # Tools
  - platform-tools                    # Platform tools
  - build-tools-28.0.3                # Build tools version
  - android-28                        # Target SDK version
  - android-21                        # Min SDK version
  - extra-android-support             # Support repo
  - extra-android-m2repository        # Support repo
  - sys-img-armeabi-v7a-android-28    # Emulator

jobs:
  include:
  - stage: "Assemble"
    script: ./gradlew assemble
  - stage: "Reports"
    name: "Unit Tests"
    script: ./gradlew jacocoTestReport
  - name: "Detekt"
    script: ./gradlew detekt

branches:
  only:
  - master

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

after_success:
- bash <(curl -s https://codecov.io/bash)
