language: android
jdk: oraclejdk8
sudo: false

script:
  - echo "script test"

deploy:
  - provider: script
    script: bash scripts/deploy.sh staging
    on:
      branch: ci/tag-deploy
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+\.[0-9]+\.[0-9]+

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
  - $HOME/.konan/cache/
  - $HOME/.konan/dependencies/
