language: android
jdk: oraclejdk8
sudo: false

android:
  components:
  - tools                             # Tools
  - platform-tools                    # Platform tools
  - build-tools-28.0.3                # Build tools version
  - android-28                        # Target SDK version
  - android-21                        # Min SDK version
  - extra-android-support             # Support repo
  - extra-android-m2repository        # Support repo
  - sys-img-armeabi-v7a-android-28    # Emulator

script:
  - ./gradlew test
  - ./gradlew lint
  - ./gradlew ktlintCheck